;;;; chibi.term.ansi.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax
         (only r7rs
               begin
               cond-expand
               export
               import
               import-for-syntax
               include
               include-ci
               syntax-rules)
         scheme.base
         scheme.write
         scheme.process-context))
    (import
      (only r7rs
            begin
            cond-expand
            export
            import
            import-for-syntax
            include
            include-ci
            syntax-rules))
    (##sys#register-compiled-module
      'chibi.term.ansi
      'chibi.term.ansi
      (scheme#list
        '(make-wrap-procedure . chibi.term.ansi#make-wrap-procedure)
        '(make-simple-escape-procedure
           .
           chibi.term.ansi#make-simple-escape-procedure))
      '((black-escape . chibi.term.ansi#black-escape)
        (red-escape . chibi.term.ansi#red-escape)
        (yellow-escape . chibi.term.ansi#yellow-escape)
        (green-escape . chibi.term.ansi#green-escape)
        (blue-escape . chibi.term.ansi#blue-escape)
        (cyan-escape . chibi.term.ansi#cyan-escape)
        (magenta-escape . chibi.term.ansi#magenta-escape)
        (white-escape . chibi.term.ansi#white-escape)
        (rgb-escape . chibi.term.ansi#rgb-escape)
        (gray-escape . chibi.term.ansi#gray-escape)
        (rgb24-escape . chibi.term.ansi#rgb24-escape)
        (reset-color-escape . chibi.term.ansi#reset-color-escape)
        (black-background-escape . chibi.term.ansi#black-background-escape)
        (red-background-escape . chibi.term.ansi#red-background-escape)
        (yellow-background-escape . chibi.term.ansi#yellow-background-escape)
        (green-background-escape . chibi.term.ansi#green-background-escape)
        (blue-background-escape . chibi.term.ansi#blue-background-escape)
        (cyan-background-escape . chibi.term.ansi#cyan-background-escape)
        (magenta-background-escape . chibi.term.ansi#magenta-background-escape)
        (white-background-escape . chibi.term.ansi#white-background-escape)
        (rgb-background-escape . chibi.term.ansi#rgb-background-escape)
        (gray-background-escape . chibi.term.ansi#gray-background-escape)
        (rgb24-background-escape . chibi.term.ansi#rgb24-background-escape)
        (reset-background-color-escape
          .
          chibi.term.ansi#reset-background-color-escape)
        (black . chibi.term.ansi#black)
        (red . chibi.term.ansi#red)
        (yellow . chibi.term.ansi#yellow)
        (green . chibi.term.ansi#green)
        (blue . chibi.term.ansi#blue)
        (cyan . chibi.term.ansi#cyan)
        (magenta . chibi.term.ansi#magenta)
        (white . chibi.term.ansi#white)
        (black-background . chibi.term.ansi#black-background)
        (red-background . chibi.term.ansi#red-background)
        (yellow-background . chibi.term.ansi#yellow-background)
        (green-background . chibi.term.ansi#green-background)
        (blue-background . chibi.term.ansi#blue-background)
        (cyan-background . chibi.term.ansi#cyan-background)
        (magenta-background . chibi.term.ansi#magenta-background)
        (white-background . chibi.term.ansi#white-background)
        (bold . chibi.term.ansi#bold)
        (underline . chibi.term.ansi#underline)
        (negative . chibi.term.ansi#negative)
        (italic . chibi.term.ansi#italic)
        (strikethrough . chibi.term.ansi#strikethrough)
        (rgb . chibi.term.ansi#rgb)
        (rgb-background . chibi.term.ansi#rgb-background)
        (gray . chibi.term.ansi#gray)
        (gray-background . chibi.term.ansi#gray-background)
        (rgb24 . chibi.term.ansi#rgb24)
        (rgb24-background . chibi.term.ansi#rgb24-background)
        (bold-escape . chibi.term.ansi#bold-escape)
        (reset-bold-escape . chibi.term.ansi#reset-bold-escape)
        (underline-escape . chibi.term.ansi#underline-escape)
        (reset-underline-escape . chibi.term.ansi#reset-underline-escape)
        (negative-escape . chibi.term.ansi#negative-escape)
        (reset-negative-escape . chibi.term.ansi#reset-negative-escape)
        (italic-escape . chibi.term.ansi#italic-escape)
        (reset-italic-escape . chibi.term.ansi#reset-italic-escape)
        (strikethrough-escape . chibi.term.ansi#strikethrough-escape)
        (reset-strikethrough-escape
          .
          chibi.term.ansi#reset-strikethrough-escape)
        (ansi-escapes-enabled? . chibi.term.ansi#ansi-escapes-enabled?))
      (scheme#list
        (scheme#cons
          '|\x04r7rschibi.term.ansi|
          (##sys#er-transformer (##core#lambda (x r c) (##core#undefined)))))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
